### ISSUE TITLE
pm2部署

### ISSUE THREAD

**Issue by mafeifan** [sunshine1125/my-house#4]
1. 服务器安装mongo https://docs.mongodb.com/manual/installation/
2. 通过pm2部署项目。先生成ssh
3. 测试环境
4. 写测试用例，建立test目录 https://github.com/nswbmw/N-blog/blob/master/book/4.14%20%E6%B5%8B%E8%AF%95.md

SSH生成key
http://19108b25.wiz03.com/share/s/0p48IB1WiN7w2yWIUS2AA_om1AdNsg1CSQgT268sTA3I4k_Q

**Comment by mafeifan** [comment]
![image](https://user-images.githubusercontent.com/4178463/37555848-041493e4-2a29-11e8-9ec6-10ed088deccf.png)

![image](https://user-images.githubusercontent.com/4178463/37555877-6b8ef780-2a29-11e8-8126-4f8a02952e09.png)


不要写死，改为从配置文件动态获取
不然一旦端口，域名发生变化或部署到服务器上就要改很多地方。

**Comment by mafeifan** [comment]
/server/config/prod.js 内直接返回配置对象就行
比如类似这样写
![image](https://user-images.githubusercontent.com/4178463/37555902-c4762346-2a29-11e8-8232-aec0fb5244ed.png)


getconfirToken() 这些共用方法，跟config没有关系，可以提取放到 helpers.js 或 common.js中
不懂的话问我

**Comment by mafeifan** [comment]
建议你多搜下别人开源的项目，学下结构组织

**Comment by sunshine1125** [comment]
图片等比例缩放，时间格式化，注册完成直接调到主页面

**Comment by mafeifan** [comment]
线上注册，登录不了。返回500。检查下后端启动没有

**Comment by mafeifan** [comment]
界面比之前好看了，
1. 先改前台，前台首页不应该是注册页面，应该是文章列表页
2. 前台的路由有 文章列表，文章详情，按分类查看文章列表，查看所有分类
